### ISSUE TITLE
Feat: support GitHub’s new Checks API

### ISSUE THREAD

**Issue by espy** [greenkeeperio/greenkeeper#822]
GitHub has [introduced a new, more detailed way of displaying statuses](https://blog.github.com/2018-05-07-introducing-checks-api/) called the Checks API, and they can have a lot more states than statuses could. Our main use of these is checking whether CI tests pass, so we were interested in Octokit’s [old getCombinedStatusForRef API](https://octokit.github.io/rest.js/#api-Repos-getCombinedStatusForRef). We’d pass in a branch SHA whenever a status event arrived and get back `failure` if _any_ of the status…es was _not_ `success`. We need to find the equivalent for the Checks API.

⚠️The Checks API is in beta and requires the `application/vnd.github.antiope-preview+json` Accept header.

### 1. Receiving Check events
Where previously we listened for `status` events from GitHub, we’ll now also have to listen for [CheckRunEvent](https://developer.github.com/v3/activity/events/types/#checkrunevent), which requires Greenkeeper to have the `checks:read` permission:

> If your GitHub App has the `checks:read` permission and subscribes to the `check_run` webhook event, you'll receive the `created` and `updated` action payloads for all check runs in your app's repository.

I’d assume the interesting one is `updated`. The payload includes an optional `check_run.conclusion` key that have the value `success`. However, this is only one check of possibly many. We need the combined status of all of them.

### 2. Getting the combined status. 
At first glance it seems like the new CheckSuite feature would allow us to get a grouped result for all runs, but a CheckSuite only includes CheckRuns from a _single_ GitHub app (maybe like when Travis runs multiple times for different node.js versions), so that’s out.

Instead, it seems like we need to [List the CheckRuns for a specific ref](https://developer.github.com/v3/checks/runs/#list-check-runs-for-a-specific-ref), which returns an array of `check_runs`, in which each CheckRun object contains a `conclusion` key, which is exactly what we want.

⚠️ This seeeeeems to return all CheckRuns, even old ones, unless you specify `filter: 'latest'` in the request. This hopefully means that if two CI services ran multiple times, it would always return the latest of _each_ possible CheckRun. If not, we can fetch all runs and dedupe by the CheckRun’s `name` key.

### 2.1 What do the conclusions mean?
Conclusions can be `success`, `failure`, `neutral`, `cancelled`, `timed_out`, or `action_required`. Currently, we require all statuses to be `success`, but that was a binary option, the only other one was `failure`. Now things are more ambiguous. My initial assumption is that if all of the runs have either the `success` or `neutral` conclusion, Greenkeeper should consider the branch as intact and the build as passing, but we should definitely have a little think about that.

🤔Note: This is my understanding of the docs as they are, none of this was actually tested yet.  

### Possible Complications
- Can a repo have both Statuses and Checks? 
- Do we assume that all checks that can report `failure` are non-optional for the repo?

## Tasks

- [x] ~Add a `github-events/check_run.js` webhook handler~ we’re going with `github-events/check_suite/complete.js` now.
- [x] Split the branch job creation part of `github-events/status.js` out into a new lib file that is used by both `github-events/status.js` and the new `github-events/check_run.js`. This new file will then need to collect Checks in addition to the `getCombinedStatusForRef` that it‘s already doing. 
- [x] Make sure the Greenkeeper GitHub App has the `checks:read` permission

**Comment by espy** [comment]
Note to self: re-runs of things checked by the Checks API automatically replace previous runs, so `latest` isn’t actually needed. Example: you re-run a Travis build. Querying Checks will still return the same amount of results, it just returns the most recent instance of each.

**Comment by espy** [comment]
Update with the reason why this is taking so long: we send the combined statuses payload all over the place and also store it in the DB, so we can’t just extend or overload that easily without being certain that our solution is backward-compatible and also works if we _only_ have checks and no statuses. Here’s how deep the combined rabbithole goes:

The combined statuses payload is passed into various jobs and then stored in the branch docs, from where it is loaded and used, for example to compose fail issue bodies (unfold the statuses details): https://github.com/greenkeeperio/greenkeeper/issues/654

### Flow

From
`status.js` (and in the `use-kits` branch its helper `on-branch-status.js`)

`combined` goes into and is upserted into the DB by:
`jobs/create-initial-pr-comment`
`jobs/create-initial-pr`
`jobs/create-initial-subgroup-pr-comment`
`jobs/create-initial-subgroup-pr`
however, these don’t actually do anything with `combined`.

after the jobs are started in `status.js`, `combined` is then passed to
`lib/handle-branch-status.js`
- if `combined.state === 'success'` -> upserts `combined` into the branchDoc in the DB as part of a `change` object when it sets the branch to deleted
- if `combined.state === 'failure'` -> passes `combined` into `open-issue.js`, where it is passed on to

`content/fail-issue.js`
which iterates over the `statuses` array from the `combined` object to display status info

It looks like these are actually the only two places statuses are actually used for anything:
1. `lib/handle-branch-status.js` uses them to determine whether to open a `fail-issue`
2. `content/fail-issue.js` uses them to display info

**Comment by espy** [comment]
Merged with #842
